name: Robot Framework Tests

on:
  push:
    branches:
      - develop
      - feature/testes-robot

jobs:
  robot-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary selenium webdriver-manager

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results cadastro.robot
