name: Robot Framework Tests

on:
  push:
    branches:
      - develop
      - feature/testes-robot

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary selenium

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Get Chromium major version
        id: get_chrome_version
        run: |
          CHROME_VER=$(/opt/hostedtoolcache/setup-chrome/chromium/*/x64/chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Full Chrome Version: $CHROME_VER"
          MAJOR_VER=$(echo $CHROME_VER | cut -d '.' -f 1)
          echo "major_version=$MAJOR_VER" >> $GITHUB_OUTPUT

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: ${{ steps.get_chrome_version.outputs.major_version }}

      - name: Run Robot Framework tests
        run: robot cadastro.robot
