name: Testes Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: laravel
          MYSQL_PASSWORD: secret
        # Removido 'ports' para evitar conflitos
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar PHP e Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql, dom, fileinfo
        coverage: none

    - name: Instalar dependências PHP
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copiar .env.example
      run: cp .env.example .env

    - name: Gerar chave do Laravel
      run: php artisan key:generate

    - name: Esperar o MySQL estar pronto
      run: |
        echo "Aguardando o MySQL iniciar..."
        for i in {1..30}; do
          if mysql -h mysql -u laravel -psecret -e "SELECT 1" &> /dev/null; then
            echo "✅ MySQL está pronto!"
            break
          fi
          echo "⏳ Ainda aguardando..."
          sleep 2
        done

    - name: Rodar migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: secret
      run: php artisan migrate:fresh --force

    - name: Rodar testes (nenhum por enquanto)
      run: php artisan test || echo "Nenhum teste implementado ainda"
